import { AppointmentCreateNestedManyWithoutUserProfilesInput } from "./AppointmentCreateNestedManyWithoutUserProfilesInput";
import { AttendanceCreateNestedManyWithoutUserProfilesInput } from "./AttendanceCreateNestedManyWithoutUserProfilesInput";
import { ChatMessageCreateNestedManyWithoutUserProfilesInput } from "./ChatMessageCreateNestedManyWithoutUserProfilesInput";
import { ChatCreateNestedManyWithoutUserProfilesInput } from "./ChatCreateNestedManyWithoutUserProfilesInput";
import { EmployeeDailyStatCreateNestedManyWithoutUserProfilesInput } from "./EmployeeDailyStatCreateNestedManyWithoutUserProfilesInput";
import { EmployeeStatCreateNestedManyWithoutUserProfilesInput } from "./EmployeeStatCreateNestedManyWithoutUserProfilesInput";
import { EmployeeTaskCreateNestedManyWithoutUserProfilesInput } from "./EmployeeTaskCreateNestedManyWithoutUserProfilesInput";
import { EmployeeWorkScheduleCreateNestedManyWithoutUserProfilesInput } from "./EmployeeWorkScheduleCreateNestedManyWithoutUserProfilesInput";
import { InputJsonValue } from "../../types";
import { LoyaltyTransactionCreateNestedManyWithoutUserProfilesInput } from "./LoyaltyTransactionCreateNestedManyWithoutUserProfilesInput";
import { NotificationCreateNestedManyWithoutUserProfilesInput } from "./NotificationCreateNestedManyWithoutUserProfilesInput";
import { OrderCreateNestedManyWithoutUserProfilesInput } from "./OrderCreateNestedManyWithoutUserProfilesInput";
import { PayrollCreateNestedManyWithoutUserProfilesInput } from "./PayrollCreateNestedManyWithoutUserProfilesInput";
import { QueueCreateNestedManyWithoutUserProfilesInput } from "./QueueCreateNestedManyWithoutUserProfilesInput";
import { SalonAccountCreateNestedManyWithoutUserProfilesInput } from "./SalonAccountCreateNestedManyWithoutUserProfilesInput";
import { SalonRatingLikeCreateNestedManyWithoutUserProfilesInput } from "./SalonRatingLikeCreateNestedManyWithoutUserProfilesInput";
import { SalonRatingCreateNestedManyWithoutUserProfilesInput } from "./SalonRatingCreateNestedManyWithoutUserProfilesInput";
import { SalonCreateNestedManyWithoutUserProfilesInput } from "./SalonCreateNestedManyWithoutUserProfilesInput";
import { SalonWhereUniqueInput } from "../salon/SalonWhereUniqueInput";
import { ScheduleCreateNestedManyWithoutUserProfilesInput } from "./ScheduleCreateNestedManyWithoutUserProfilesInput";
import { TimeSlotCreateNestedManyWithoutUserProfilesInput } from "./TimeSlotCreateNestedManyWithoutUserProfilesInput";
import { UserAccountCreateNestedManyWithoutUserProfilesInput } from "./UserAccountCreateNestedManyWithoutUserProfilesInput";
import { UserAddressCreateNestedManyWithoutUserProfilesInput } from "./UserAddressCreateNestedManyWithoutUserProfilesInput";
import { UserBankCardCreateNestedManyWithoutUserProfilesInput } from "./UserBankCardCreateNestedManyWithoutUserProfilesInput";
import { UserFavoriteMasterCreateNestedManyWithoutUserProfilesInput } from "./UserFavoriteMasterCreateNestedManyWithoutUserProfilesInput";
import { UserFavoriteSalonCreateNestedManyWithoutUserProfilesInput } from "./UserFavoriteSalonCreateNestedManyWithoutUserProfilesInput";
import { UserGenderWhereUniqueInput } from "../userGender/UserGenderWhereUniqueInput";
import { UserNotificationSettingWhereUniqueInput } from "../userNotificationSetting/UserNotificationSettingWhereUniqueInput";
import { UserRatingCreateNestedManyWithoutUserProfilesInput } from "./UserRatingCreateNestedManyWithoutUserProfilesInput";

export type UserProfileCreateInput = {
  appointments?: AppointmentCreateNestedManyWithoutUserProfilesInput;
  attendances?: AttendanceCreateNestedManyWithoutUserProfilesInput;
  avatarUrl?: string | null;
  bio?: string | null;
  chatMessages?: ChatMessageCreateNestedManyWithoutUserProfilesInput;
  chatsChatsUserATouserProfiles?: ChatCreateNestedManyWithoutUserProfilesInput;
  chatsChatsUserBTouserProfiles?: ChatCreateNestedManyWithoutUserProfilesInput;
  chatsChatsUsersTouserProfiles?: ChatCreateNestedManyWithoutUserProfilesInput;
  createdAt?: Date | null;
  dateOfBirth?: Date | null;
  deletedAt?: Date | null;
  email?: string | null;
  employeeDailyStats?: EmployeeDailyStatCreateNestedManyWithoutUserProfilesInput;
  employeeDismissalAt?: Date | null;
  employeeEmploymentAt?: Date | null;
  employeeStats?: EmployeeStatCreateNestedManyWithoutUserProfilesInput;
  employeeTasks?: EmployeeTaskCreateNestedManyWithoutUserProfilesInput;
  employeeWorkSchedules?: EmployeeWorkScheduleCreateNestedManyWithoutUserProfilesInput;
  firstName?: string | null;
  fullName?: string | null;
  fullRegistered?: boolean | null;
  hiredDate?: Date | null;
  isAdmin?: boolean | null;
  isBarber?: boolean | null;
  isEmployee?: boolean | null;
  jobTitle?: string | null;
  lastName?: string | null;
  location?: InputJsonValue;
  loyaltyPoints?: number | null;
  loyaltyTransactions?: LoyaltyTransactionCreateNestedManyWithoutUserProfilesInput;
  notifications?: NotificationCreateNestedManyWithoutUserProfilesInput;
  ordersOrdersEmployeeIdTouserProfiles?: OrderCreateNestedManyWithoutUserProfilesInput;
  ordersOrdersUserIdTouserProfiles?: OrderCreateNestedManyWithoutUserProfilesInput;
  payroll?: PayrollCreateNestedManyWithoutUserProfilesInput;
  phone?: string | null;
  queuesQueuesEmployeeIdTouserProfiles?: QueueCreateNestedManyWithoutUserProfilesInput;
  queuesQueuesUserIdTouserProfiles?: QueueCreateNestedManyWithoutUserProfilesInput;
  roles: string;
  salonAccounts?: SalonAccountCreateNestedManyWithoutUserProfilesInput;
  salonRatingLikesSalonRatingLikesUserIdTouserProfiles?: SalonRatingLikeCreateNestedManyWithoutUserProfilesInput;
  salonRatingLikesSalonRatingLikesVoterIdTouserProfiles?: SalonRatingLikeCreateNestedManyWithoutUserProfilesInput;
  salonRatingsSalonRatingsUserIdTouserProfiles?: SalonRatingCreateNestedManyWithoutUserProfilesInput;
  salonRatingsSalonRatingsVoterIdTouserProfiles?: SalonRatingCreateNestedManyWithoutUserProfilesInput;
  salonsSalonsSalonAdminIdTouserProfiles?: SalonCreateNestedManyWithoutUserProfilesInput;
  salonsUserProfilesSalonIdTosalons?: SalonWhereUniqueInput | null;
  scheduleScheduleBarberIdTouserProfiles?: ScheduleCreateNestedManyWithoutUserProfilesInput;
  scheduleScheduleUserIdTouserProfiles?: ScheduleCreateNestedManyWithoutUserProfilesInput;
  timeSlots?: TimeSlotCreateNestedManyWithoutUserProfilesInput;
  updatedAt?: Date | null;
  userAccounts?: UserAccountCreateNestedManyWithoutUserProfilesInput;
  userAddresses?: UserAddressCreateNestedManyWithoutUserProfilesInput;
  userBankCards?: UserBankCardCreateNestedManyWithoutUserProfilesInput;
  userFavoriteMastersUserFavoriteMastersMasterIdTouserProfiles?: UserFavoriteMasterCreateNestedManyWithoutUserProfilesInput;
  userFavoriteMastersUserFavoriteMastersUserIdTouserProfiles?: UserFavoriteMasterCreateNestedManyWithoutUserProfilesInput;
  userFavoriteSalons?: UserFavoriteSalonCreateNestedManyWithoutUserProfilesInput;
  userGenders?: UserGenderWhereUniqueInput | null;
  userNotificationSettings?: UserNotificationSettingWhereUniqueInput | null;
  userRatingsUserRatingsOwnerTouserProfiles?: UserRatingCreateNestedManyWithoutUserProfilesInput;
  userRatingsUserRatingsUserIdTouserProfiles?: UserRatingCreateNestedManyWithoutUserProfilesInput;
  username?: string | null;
  website?: string | null;
};
