import { AppointmentListRelationFilter } from "../appointment/AppointmentListRelationFilter";
import { AttendanceListRelationFilter } from "../attendance/AttendanceListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ChatMessageListRelationFilter } from "../chatMessage/ChatMessageListRelationFilter";
import { ChatListRelationFilter } from "../chat/ChatListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { EmployeeDailyStatListRelationFilter } from "../employeeDailyStat/EmployeeDailyStatListRelationFilter";
import { EmployeeStatListRelationFilter } from "../employeeStat/EmployeeStatListRelationFilter";
import { EmployeeTaskListRelationFilter } from "../employeeTask/EmployeeTaskListRelationFilter";
import { EmployeeWorkScheduleListRelationFilter } from "../employeeWorkSchedule/EmployeeWorkScheduleListRelationFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { LoyaltyTransactionListRelationFilter } from "../loyaltyTransaction/LoyaltyTransactionListRelationFilter";
import { NotificationListRelationFilter } from "../notification/NotificationListRelationFilter";
import { OrderListRelationFilter } from "../order/OrderListRelationFilter";
import { PayrollListRelationFilter } from "../payroll/PayrollListRelationFilter";
import { QueueListRelationFilter } from "../queue/QueueListRelationFilter";
import { SalonAccountListRelationFilter } from "../salonAccount/SalonAccountListRelationFilter";
import { SalonRatingLikeListRelationFilter } from "../salonRatingLike/SalonRatingLikeListRelationFilter";
import { SalonRatingListRelationFilter } from "../salonRating/SalonRatingListRelationFilter";
import { SalonListRelationFilter } from "../salon/SalonListRelationFilter";
import { SalonWhereUniqueInput } from "../salon/SalonWhereUniqueInput";
import { ScheduleListRelationFilter } from "../schedule/ScheduleListRelationFilter";
import { TimeSlotListRelationFilter } from "../timeSlot/TimeSlotListRelationFilter";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { UserAccountListRelationFilter } from "../userAccount/UserAccountListRelationFilter";
import { UserAddressListRelationFilter } from "../userAddress/UserAddressListRelationFilter";
import { UserBankCardListRelationFilter } from "../userBankCard/UserBankCardListRelationFilter";
import { UserFavoriteMasterListRelationFilter } from "../userFavoriteMaster/UserFavoriteMasterListRelationFilter";
import { UserFavoriteSalonListRelationFilter } from "../userFavoriteSalon/UserFavoriteSalonListRelationFilter";
import { UserGenderWhereUniqueInput } from "../userGender/UserGenderWhereUniqueInput";
import { UserNotificationSettingWhereUniqueInput } from "../userNotificationSetting/UserNotificationSettingWhereUniqueInput";
import { UserRatingListRelationFilter } from "../userRating/UserRatingListRelationFilter";

export type UserProfileWhereInput = {
  appointments?: AppointmentListRelationFilter;
  attendances?: AttendanceListRelationFilter;
  avatarUrl?: StringNullableFilter;
  bio?: StringNullableFilter;
  chatMessages?: ChatMessageListRelationFilter;
  chatsChatsUserATouserProfiles?: ChatListRelationFilter;
  chatsChatsUserBTouserProfiles?: ChatListRelationFilter;
  chatsChatsUsersTouserProfiles?: ChatListRelationFilter;
  createdAt?: DateTimeNullableFilter;
  dateOfBirth?: DateTimeNullableFilter;
  deletedAt?: DateTimeNullableFilter;
  email?: StringNullableFilter;
  employeeDailyStats?: EmployeeDailyStatListRelationFilter;
  employeeDismissalAt?: DateTimeNullableFilter;
  employeeEmploymentAt?: DateTimeNullableFilter;
  employeeStats?: EmployeeStatListRelationFilter;
  employeeTasks?: EmployeeTaskListRelationFilter;
  employeeWorkSchedules?: EmployeeWorkScheduleListRelationFilter;
  firstName?: StringNullableFilter;
  fullName?: StringNullableFilter;
  fullRegistered?: BooleanNullableFilter;
  hiredDate?: DateTimeNullableFilter;
  id?: StringFilter;
  isAdmin?: BooleanNullableFilter;
  isBarber?: BooleanNullableFilter;
  isEmployee?: BooleanNullableFilter;
  jobTitle?: StringNullableFilter;
  lastName?: StringNullableFilter;
  loyaltyPoints?: IntNullableFilter;
  loyaltyTransactions?: LoyaltyTransactionListRelationFilter;
  notifications?: NotificationListRelationFilter;
  ordersOrdersEmployeeIdTouserProfiles?: OrderListRelationFilter;
  ordersOrdersUserIdTouserProfiles?: OrderListRelationFilter;
  payroll?: PayrollListRelationFilter;
  phone?: StringNullableFilter;
  queuesQueuesEmployeeIdTouserProfiles?: QueueListRelationFilter;
  queuesQueuesUserIdTouserProfiles?: QueueListRelationFilter;
  salonAccounts?: SalonAccountListRelationFilter;
  salonRatingLikesSalonRatingLikesUserIdTouserProfiles?: SalonRatingLikeListRelationFilter;
  salonRatingLikesSalonRatingLikesVoterIdTouserProfiles?: SalonRatingLikeListRelationFilter;
  salonRatingsSalonRatingsUserIdTouserProfiles?: SalonRatingListRelationFilter;
  salonRatingsSalonRatingsVoterIdTouserProfiles?: SalonRatingListRelationFilter;
  salonsSalonsSalonAdminIdTouserProfiles?: SalonListRelationFilter;
  salonsUserProfilesSalonIdTosalons?: SalonWhereUniqueInput;
  scheduleScheduleBarberIdTouserProfiles?: ScheduleListRelationFilter;
  scheduleScheduleUserIdTouserProfiles?: ScheduleListRelationFilter;
  timeSlots?: TimeSlotListRelationFilter;
  updatedAt?: DateTimeNullableFilter;
  user?: UserWhereUniqueInput;
  userAccounts?: UserAccountListRelationFilter;
  userAddresses?: UserAddressListRelationFilter;
  userBankCards?: UserBankCardListRelationFilter;
  userFavoriteMastersUserFavoriteMastersMasterIdTouserProfiles?: UserFavoriteMasterListRelationFilter;
  userFavoriteMastersUserFavoriteMastersUserIdTouserProfiles?: UserFavoriteMasterListRelationFilter;
  userFavoriteSalons?: UserFavoriteSalonListRelationFilter;
  userGenders?: UserGenderWhereUniqueInput;
  userNotificationSettings?: UserNotificationSettingWhereUniqueInput;
  userRatingsUserRatingsOwnerTouserProfiles?: UserRatingListRelationFilter;
  userRatingsUserRatingsUserIdTouserProfiles?: UserRatingListRelationFilter;
  website?: StringNullableFilter;
};
