import { Appointment } from "../appointment/Appointment";
import { Attendance } from "../attendance/Attendance";
import { ChatMessage } from "../chatMessage/ChatMessage";
import { Chat } from "../chat/Chat";
import { EmployeeDailyStat } from "../employeeDailyStat/EmployeeDailyStat";
import { EmployeeStat } from "../employeeStat/EmployeeStat";
import { EmployeeTask } from "../employeeTask/EmployeeTask";
import { EmployeeWorkSchedule } from "../employeeWorkSchedule/EmployeeWorkSchedule";
import { LoyaltyTransaction } from "../loyaltyTransaction/LoyaltyTransaction";
import { Notification } from "../notification/Notification";
import { Order } from "../order/Order";
import { Payroll } from "../payroll/Payroll";
import { Queue } from "../queue/Queue";
import { SalonAccount } from "../salonAccount/SalonAccount";
import { SalonRatingLike } from "../salonRatingLike/SalonRatingLike";
import { SalonRating } from "../salonRating/SalonRating";
import { Salon } from "../salon/Salon";
import { Schedule } from "../schedule/Schedule";
import { TimeSlot } from "../timeSlot/TimeSlot";
import { User } from "../user/User";
import { UserAccount } from "../userAccount/UserAccount";
import { UserAddress } from "../userAddress/UserAddress";
import { UserBankCard } from "../userBankCard/UserBankCard";
import { UserFavoriteMaster } from "../userFavoriteMaster/UserFavoriteMaster";
import { UserFavoriteSalon } from "../userFavoriteSalon/UserFavoriteSalon";
import { UserGender } from "../userGender/UserGender";
import { UserNotificationSetting } from "../userNotificationSetting/UserNotificationSetting";
import { UserRating } from "../userRating/UserRating";

export type UserProfile = {
  appointments?: Array<Appointment>;
  attendances?: Array<Attendance>;
  avatarUrl: string | null;
  bio: string | null;
  chatMessages?: Array<ChatMessage>;
  chatsChatsUserATouserProfiles?: Array<Chat>;
  chatsChatsUserBTouserProfiles?: Array<Chat>;
  chatsChatsUsersTouserProfiles?: Array<Chat>;
  createdAt: Date | null;
  dateOfBirth: Date | null;
  deletedAt: Date | null;
  email: string | null;
  employeeDailyStats?: Array<EmployeeDailyStat>;
  employeeDismissalAt: Date | null;
  employeeEmploymentAt: Date | null;
  employeeStats?: Array<EmployeeStat>;
  employeeTasks?: Array<EmployeeTask>;
  employeeWorkSchedules?: Array<EmployeeWorkSchedule>;
  firstName: string | null;
  fullName: string | null;
  fullRegistered: boolean | null;
  hiredDate: Date | null;
  id: string;
  isAdmin: boolean | null;
  isBarber: boolean | null;
  isEmployee: boolean | null;
  jobTitle: string | null;
  lastName: string | null;
  location: string | null;
  loyaltyPoints: number | null;
  loyaltyTransactions?: Array<LoyaltyTransaction>;
  notifications?: Array<Notification>;
  ordersOrdersEmployeeIdTouserProfiles?: Array<Order>;
  ordersOrdersUserIdTouserProfiles?: Array<Order>;
  payroll?: Array<Payroll>;
  phone: string | null;
  queuesQueuesEmployeeIdTouserProfiles?: Array<Queue>;
  queuesQueuesUserIdTouserProfiles?: Array<Queue>;
  salonAccounts?: Array<SalonAccount>;
  salonRatingLikesSalonRatingLikesUserIdTouserProfiles?: Array<SalonRatingLike>;
  salonRatingLikesSalonRatingLikesVoterIdTouserProfiles?: Array<SalonRatingLike>;
  salonRatingsSalonRatingsUserIdTouserProfiles?: Array<SalonRating>;
  salonRatingsSalonRatingsVoterIdTouserProfiles?: Array<SalonRating>;
  salonsSalonsSalonAdminIdTouserProfiles?: Array<Salon>;
  salonsUserProfilesSalonIdTosalons?: Salon | null;
  scheduleScheduleBarberIdTouserProfiles?: Array<Schedule>;
  scheduleScheduleUserIdTouserProfiles?: Array<Schedule>;
  timeSlots?: Array<TimeSlot>;
  updatedAt: Date | null;
  user?: User | null;
  userAccounts?: Array<UserAccount>;
  userAddresses?: Array<UserAddress>;
  userBankCards?: Array<UserBankCard>;
  userFavoriteMastersUserFavoriteMastersMasterIdTouserProfiles?: Array<UserFavoriteMaster>;
  userFavoriteMastersUserFavoriteMastersUserIdTouserProfiles?: Array<UserFavoriteMaster>;
  userFavoriteSalons?: Array<UserFavoriteSalon>;
  userGenders?: UserGender | null;
  userNotificationSettings?: UserNotificationSetting | null;
  userRatingsUserRatingsOwnerTouserProfiles?: Array<UserRating>;
  userRatingsUserRatingsUserIdTouserProfiles?: Array<UserRating>;
  website: string | null;
};
