import { AppointmentUpdateManyWithoutUserProfilesInput } from "./AppointmentUpdateManyWithoutUserProfilesInput";
import { AttendanceUpdateManyWithoutUserProfilesInput } from "./AttendanceUpdateManyWithoutUserProfilesInput";
import { ChatMessageUpdateManyWithoutUserProfilesInput } from "./ChatMessageUpdateManyWithoutUserProfilesInput";
import { ChatUpdateManyWithoutUserProfilesInput } from "./ChatUpdateManyWithoutUserProfilesInput";
import { EmployeeDailyStatUpdateManyWithoutUserProfilesInput } from "./EmployeeDailyStatUpdateManyWithoutUserProfilesInput";
import { EmployeeStatUpdateManyWithoutUserProfilesInput } from "./EmployeeStatUpdateManyWithoutUserProfilesInput";
import { EmployeeTaskUpdateManyWithoutUserProfilesInput } from "./EmployeeTaskUpdateManyWithoutUserProfilesInput";
import { EmployeeWorkScheduleUpdateManyWithoutUserProfilesInput } from "./EmployeeWorkScheduleUpdateManyWithoutUserProfilesInput";
import { LoyaltyTransactionUpdateManyWithoutUserProfilesInput } from "./LoyaltyTransactionUpdateManyWithoutUserProfilesInput";
import { NotificationUpdateManyWithoutUserProfilesInput } from "./NotificationUpdateManyWithoutUserProfilesInput";
import { OrderUpdateManyWithoutUserProfilesInput } from "./OrderUpdateManyWithoutUserProfilesInput";
import { PayrollUpdateManyWithoutUserProfilesInput } from "./PayrollUpdateManyWithoutUserProfilesInput";
import { QueueUpdateManyWithoutUserProfilesInput } from "./QueueUpdateManyWithoutUserProfilesInput";
import { SalonAccountUpdateManyWithoutUserProfilesInput } from "./SalonAccountUpdateManyWithoutUserProfilesInput";
import { SalonRatingLikeUpdateManyWithoutUserProfilesInput } from "./SalonRatingLikeUpdateManyWithoutUserProfilesInput";
import { SalonRatingUpdateManyWithoutUserProfilesInput } from "./SalonRatingUpdateManyWithoutUserProfilesInput";
import { SalonUpdateManyWithoutUserProfilesInput } from "./SalonUpdateManyWithoutUserProfilesInput";
import { SalonWhereUniqueInput } from "../salon/SalonWhereUniqueInput";
import { ScheduleUpdateManyWithoutUserProfilesInput } from "./ScheduleUpdateManyWithoutUserProfilesInput";
import { TimeSlotUpdateManyWithoutUserProfilesInput } from "./TimeSlotUpdateManyWithoutUserProfilesInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { UserAccountUpdateManyWithoutUserProfilesInput } from "./UserAccountUpdateManyWithoutUserProfilesInput";
import { UserAddressUpdateManyWithoutUserProfilesInput } from "./UserAddressUpdateManyWithoutUserProfilesInput";
import { UserBankCardUpdateManyWithoutUserProfilesInput } from "./UserBankCardUpdateManyWithoutUserProfilesInput";
import { UserFavoriteMasterUpdateManyWithoutUserProfilesInput } from "./UserFavoriteMasterUpdateManyWithoutUserProfilesInput";
import { UserFavoriteSalonUpdateManyWithoutUserProfilesInput } from "./UserFavoriteSalonUpdateManyWithoutUserProfilesInput";
import { UserGenderWhereUniqueInput } from "../userGender/UserGenderWhereUniqueInput";
import { UserNotificationSettingWhereUniqueInput } from "../userNotificationSetting/UserNotificationSettingWhereUniqueInput";
import { UserRatingUpdateManyWithoutUserProfilesInput } from "./UserRatingUpdateManyWithoutUserProfilesInput";

export type UserProfileUpdateInput = {
  appointments?: AppointmentUpdateManyWithoutUserProfilesInput;
  attendances?: AttendanceUpdateManyWithoutUserProfilesInput;
  avatarUrl?: string | null;
  bio?: string | null;
  chatMessages?: ChatMessageUpdateManyWithoutUserProfilesInput;
  chatsChatsUserATouserProfiles?: ChatUpdateManyWithoutUserProfilesInput;
  chatsChatsUserBTouserProfiles?: ChatUpdateManyWithoutUserProfilesInput;
  chatsChatsUsersTouserProfiles?: ChatUpdateManyWithoutUserProfilesInput;
  createdAt?: Date | null;
  dateOfBirth?: Date | null;
  deletedAt?: Date | null;
  email?: string | null;
  employeeDailyStats?: EmployeeDailyStatUpdateManyWithoutUserProfilesInput;
  employeeDismissalAt?: Date | null;
  employeeEmploymentAt?: Date | null;
  employeeStats?: EmployeeStatUpdateManyWithoutUserProfilesInput;
  employeeTasks?: EmployeeTaskUpdateManyWithoutUserProfilesInput;
  employeeWorkSchedules?: EmployeeWorkScheduleUpdateManyWithoutUserProfilesInput;
  firstName?: string | null;
  fullName?: string | null;
  fullRegistered?: boolean | null;
  hiredDate?: Date | null;
  isAdmin?: boolean | null;
  isBarber?: boolean | null;
  isEmployee?: boolean | null;
  jobTitle?: string | null;
  lastName?: string | null;
  location?: string | null;
  loyaltyPoints?: number | null;
  loyaltyTransactions?: LoyaltyTransactionUpdateManyWithoutUserProfilesInput;
  notifications?: NotificationUpdateManyWithoutUserProfilesInput;
  ordersOrdersEmployeeIdTouserProfiles?: OrderUpdateManyWithoutUserProfilesInput;
  ordersOrdersUserIdTouserProfiles?: OrderUpdateManyWithoutUserProfilesInput;
  payroll?: PayrollUpdateManyWithoutUserProfilesInput;
  phone?: string | null;
  queuesQueuesEmployeeIdTouserProfiles?: QueueUpdateManyWithoutUserProfilesInput;
  queuesQueuesUserIdTouserProfiles?: QueueUpdateManyWithoutUserProfilesInput;
  salonAccounts?: SalonAccountUpdateManyWithoutUserProfilesInput;
  salonRatingLikesSalonRatingLikesUserIdTouserProfiles?: SalonRatingLikeUpdateManyWithoutUserProfilesInput;
  salonRatingLikesSalonRatingLikesVoterIdTouserProfiles?: SalonRatingLikeUpdateManyWithoutUserProfilesInput;
  salonRatingsSalonRatingsUserIdTouserProfiles?: SalonRatingUpdateManyWithoutUserProfilesInput;
  salonRatingsSalonRatingsVoterIdTouserProfiles?: SalonRatingUpdateManyWithoutUserProfilesInput;
  salonsSalonsSalonAdminIdTouserProfiles?: SalonUpdateManyWithoutUserProfilesInput;
  salonsUserProfilesSalonIdTosalons?: SalonWhereUniqueInput | null;
  scheduleScheduleBarberIdTouserProfiles?: ScheduleUpdateManyWithoutUserProfilesInput;
  scheduleScheduleUserIdTouserProfiles?: ScheduleUpdateManyWithoutUserProfilesInput;
  timeSlots?: TimeSlotUpdateManyWithoutUserProfilesInput;
  updatedAt?: Date | null;
  user?: UserWhereUniqueInput | null;
  userAccounts?: UserAccountUpdateManyWithoutUserProfilesInput;
  userAddresses?: UserAddressUpdateManyWithoutUserProfilesInput;
  userBankCards?: UserBankCardUpdateManyWithoutUserProfilesInput;
  userFavoriteMastersUserFavoriteMastersMasterIdTouserProfiles?: UserFavoriteMasterUpdateManyWithoutUserProfilesInput;
  userFavoriteMastersUserFavoriteMastersUserIdTouserProfiles?: UserFavoriteMasterUpdateManyWithoutUserProfilesInput;
  userFavoriteSalons?: UserFavoriteSalonUpdateManyWithoutUserProfilesInput;
  userGenders?: UserGenderWhereUniqueInput | null;
  userNotificationSettings?: UserNotificationSettingWhereUniqueInput | null;
  userRatingsUserRatingsOwnerTouserProfiles?: UserRatingUpdateManyWithoutUserProfilesInput;
  userRatingsUserRatingsUserIdTouserProfiles?: UserRatingUpdateManyWithoutUserProfilesInput;
  website?: string | null;
};
