/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Identity } from "./Identity";
import { IdentityCountArgs } from "./IdentityCountArgs";
import { IdentityFindManyArgs } from "./IdentityFindManyArgs";
import { IdentityFindUniqueArgs } from "./IdentityFindUniqueArgs";
import { CreateIdentityArgs } from "./CreateIdentityArgs";
import { UpdateIdentityArgs } from "./UpdateIdentityArgs";
import { DeleteIdentityArgs } from "./DeleteIdentityArgs";
import { User } from "../../user/base/User";
import { IdentityService } from "../identity.service";
@graphql.Resolver(() => Identity)
export class IdentityResolverBase {
  constructor(protected readonly service: IdentityService) {}

  async _identitiesMeta(
    @graphql.Args() args: IdentityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Identity])
  async identities(
    @graphql.Args() args: IdentityFindManyArgs
  ): Promise<Identity[]> {
    return this.service.identities(args);
  }

  @graphql.Query(() => Identity, { nullable: true })
  async identity(
    @graphql.Args() args: IdentityFindUniqueArgs
  ): Promise<Identity | null> {
    const result = await this.service.identity(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Identity)
  async createIdentity(
    @graphql.Args() args: CreateIdentityArgs
  ): Promise<Identity> {
    return await this.service.createIdentity({
      ...args,
      data: {
        ...args.data,

        users: {
          connect: args.data.users,
        },
      },
    });
  }

  @graphql.Mutation(() => Identity)
  async updateIdentity(
    @graphql.Args() args: UpdateIdentityArgs
  ): Promise<Identity | null> {
    try {
      return await this.service.updateIdentity({
        ...args,
        data: {
          ...args.data,

          users: {
            connect: args.data.users,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Identity)
  async deleteIdentity(
    @graphql.Args() args: DeleteIdentityArgs
  ): Promise<Identity | null> {
    try {
      return await this.service.deleteIdentity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "users",
  })
  async getUsers(@graphql.Parent() parent: Identity): Promise<User | null> {
    const result = await this.service.getUsers(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
