import { AttendanceUpdateManyWithoutSalonsInput } from "./AttendanceUpdateManyWithoutSalonsInput";
import { InputJsonValue } from "../../types";
import { EmployeeDailyStatUpdateManyWithoutSalonsInput } from "./EmployeeDailyStatUpdateManyWithoutSalonsInput";
import { EmployeeStatUpdateManyWithoutSalonsInput } from "./EmployeeStatUpdateManyWithoutSalonsInput";
import { EmployeeTaskUpdateManyWithoutSalonsInput } from "./EmployeeTaskUpdateManyWithoutSalonsInput";
import { EmployeeWorkScheduleUpdateManyWithoutSalonsInput } from "./EmployeeWorkScheduleUpdateManyWithoutSalonsInput";
import { OrderUpdateManyWithoutSalonsInput } from "./OrderUpdateManyWithoutSalonsInput";
import { QueueUpdateManyWithoutSalonsInput } from "./QueueUpdateManyWithoutSalonsInput";
import { SalonAccountUpdateManyWithoutSalonsInput } from "./SalonAccountUpdateManyWithoutSalonsInput";
import { SalonRatingLikeUpdateManyWithoutSalonsInput } from "./SalonRatingLikeUpdateManyWithoutSalonsInput";
import { SalonRatingUpdateManyWithoutSalonsInput } from "./SalonRatingUpdateManyWithoutSalonsInput";
import { SalonServiceUpdateManyWithoutSalonsInput } from "./SalonServiceUpdateManyWithoutSalonsInput";
import { TimeSlotUpdateManyWithoutSalonsInput } from "./TimeSlotUpdateManyWithoutSalonsInput";
import { UserAccountUpdateManyWithoutSalonsInput } from "./UserAccountUpdateManyWithoutSalonsInput";
import { UserFavoriteSalonUpdateManyWithoutSalonsInput } from "./UserFavoriteSalonUpdateManyWithoutSalonsInput";
import { UserProfileWhereUniqueInput } from "../userProfile/UserProfileWhereUniqueInput";
import { UserProfileUpdateManyWithoutSalonsInput } from "./UserProfileUpdateManyWithoutSalonsInput";

export type SalonUpdateInput = {
  active?: boolean | null;
  address?: string | null;
  attendances?: AttendanceUpdateManyWithoutSalonsInput;
  barbers?: string | null;
  categories?: InputJsonValue;
  closeTime?: Date | null;
  description?: string | null;
  email?: string | null;
  employeeDailyStats?: EmployeeDailyStatUpdateManyWithoutSalonsInput;
  employeeStats?: EmployeeStatUpdateManyWithoutSalonsInput;
  employeeTasks?: EmployeeTaskUpdateManyWithoutSalonsInput;
  employeeWorkSchedules?: EmployeeWorkScheduleUpdateManyWithoutSalonsInput;
  images?: string;
  img?: string | null;
  latLng?: InputJsonValue;
  location?: InputJsonValue;
  logo?: string | null;
  name?: string;
  open?: boolean | null;
  openTime?: Date | null;
  orders?: OrderUpdateManyWithoutSalonsInput;
  phone?: string;
  queues?: QueueUpdateManyWithoutSalonsInput;
  salonAccounts?: SalonAccountUpdateManyWithoutSalonsInput;
  salonRatingLikes?: SalonRatingLikeUpdateManyWithoutSalonsInput;
  salonRatings?: SalonRatingUpdateManyWithoutSalonsInput;
  salonServices?: SalonServiceUpdateManyWithoutSalonsInput;
  timeSlots?: TimeSlotUpdateManyWithoutSalonsInput;
  timezone?: string;
  updatedAt?: Date | null;
  userAccounts?: UserAccountUpdateManyWithoutSalonsInput;
  userFavoriteSalons?: UserFavoriteSalonUpdateManyWithoutSalonsInput;
  userProfilesSalonsSalonAdminIdTouserProfiles?: UserProfileWhereUniqueInput | null;
  userProfilesUserProfilesSalonIdTosalons?: UserProfileUpdateManyWithoutSalonsInput;
  website?: string | null;
};
