import { AttendanceCreateNestedManyWithoutSalonsInput } from "./AttendanceCreateNestedManyWithoutSalonsInput";
import { InputJsonValue } from "../../types";
import { EmployeeDailyStatCreateNestedManyWithoutSalonsInput } from "./EmployeeDailyStatCreateNestedManyWithoutSalonsInput";
import { EmployeeStatCreateNestedManyWithoutSalonsInput } from "./EmployeeStatCreateNestedManyWithoutSalonsInput";
import { EmployeeTaskCreateNestedManyWithoutSalonsInput } from "./EmployeeTaskCreateNestedManyWithoutSalonsInput";
import { EmployeeWorkScheduleCreateNestedManyWithoutSalonsInput } from "./EmployeeWorkScheduleCreateNestedManyWithoutSalonsInput";
import { OrderCreateNestedManyWithoutSalonsInput } from "./OrderCreateNestedManyWithoutSalonsInput";
import { QueueCreateNestedManyWithoutSalonsInput } from "./QueueCreateNestedManyWithoutSalonsInput";
import { SalonAccountCreateNestedManyWithoutSalonsInput } from "./SalonAccountCreateNestedManyWithoutSalonsInput";
import { SalonRatingLikeCreateNestedManyWithoutSalonsInput } from "./SalonRatingLikeCreateNestedManyWithoutSalonsInput";
import { SalonRatingCreateNestedManyWithoutSalonsInput } from "./SalonRatingCreateNestedManyWithoutSalonsInput";
import { SalonServiceCreateNestedManyWithoutSalonsInput } from "./SalonServiceCreateNestedManyWithoutSalonsInput";
import { TimeSlotCreateNestedManyWithoutSalonsInput } from "./TimeSlotCreateNestedManyWithoutSalonsInput";
import { UserAccountCreateNestedManyWithoutSalonsInput } from "./UserAccountCreateNestedManyWithoutSalonsInput";
import { UserFavoriteSalonCreateNestedManyWithoutSalonsInput } from "./UserFavoriteSalonCreateNestedManyWithoutSalonsInput";
import { UserProfileWhereUniqueInput } from "../userProfile/UserProfileWhereUniqueInput";
import { UserProfileCreateNestedManyWithoutSalonsInput } from "./UserProfileCreateNestedManyWithoutSalonsInput";

export type SalonCreateInput = {
  active?: boolean | null;
  address?: string | null;
  attendances?: AttendanceCreateNestedManyWithoutSalonsInput;
  barbers?: string | null;
  categories: InputJsonValue;
  closeTime?: Date | null;
  description?: string | null;
  email?: string | null;
  employeeDailyStats?: EmployeeDailyStatCreateNestedManyWithoutSalonsInput;
  employeeStats?: EmployeeStatCreateNestedManyWithoutSalonsInput;
  employeeTasks?: EmployeeTaskCreateNestedManyWithoutSalonsInput;
  employeeWorkSchedules?: EmployeeWorkScheduleCreateNestedManyWithoutSalonsInput;
  images: string;
  img?: string | null;
  latLng?: InputJsonValue;
  location?: InputJsonValue;
  logo?: string | null;
  name: string;
  open?: boolean | null;
  openTime?: Date | null;
  orders?: OrderCreateNestedManyWithoutSalonsInput;
  phone: string;
  queues?: QueueCreateNestedManyWithoutSalonsInput;
  salonAccounts?: SalonAccountCreateNestedManyWithoutSalonsInput;
  salonRatingLikes?: SalonRatingLikeCreateNestedManyWithoutSalonsInput;
  salonRatings?: SalonRatingCreateNestedManyWithoutSalonsInput;
  salonServices?: SalonServiceCreateNestedManyWithoutSalonsInput;
  timeSlots?: TimeSlotCreateNestedManyWithoutSalonsInput;
  timezone: string;
  updatedAt?: Date | null;
  userAccounts?: UserAccountCreateNestedManyWithoutSalonsInput;
  userFavoriteSalons?: UserFavoriteSalonCreateNestedManyWithoutSalonsInput;
  userProfilesSalonsSalonAdminIdTouserProfiles?: UserProfileWhereUniqueInput | null;
  userProfilesUserProfilesSalonIdTosalons?: UserProfileCreateNestedManyWithoutSalonsInput;
  website?: string | null;
};
