import { Attendance } from "../attendance/Attendance";
import { JsonValue } from "type-fest";
import { EmployeeDailyStat } from "../employeeDailyStat/EmployeeDailyStat";
import { EmployeeStat } from "../employeeStat/EmployeeStat";
import { EmployeeTask } from "../employeeTask/EmployeeTask";
import { EmployeeWorkSchedule } from "../employeeWorkSchedule/EmployeeWorkSchedule";
import { Order } from "../order/Order";
import { Queue } from "../queue/Queue";
import { SalonAccount } from "../salonAccount/SalonAccount";
import { SalonRatingLike } from "../salonRatingLike/SalonRatingLike";
import { SalonRating } from "../salonRating/SalonRating";
import { SalonService } from "../salonService/SalonService";
import { TimeSlot } from "../timeSlot/TimeSlot";
import { UserAccount } from "../userAccount/UserAccount";
import { UserFavoriteSalon } from "../userFavoriteSalon/UserFavoriteSalon";
import { UserProfile } from "../userProfile/UserProfile";

export type Salon = {
  active: boolean | null;
  address: string | null;
  attendances?: Array<Attendance>;
  barbers: string | null;
  categories: JsonValue;
  closeTime: Date | null;
  createdAt: Date | null;
  description: string | null;
  email: string | null;
  employeeDailyStats?: Array<EmployeeDailyStat>;
  employeeStats?: Array<EmployeeStat>;
  employeeTasks?: Array<EmployeeTask>;
  employeeWorkSchedules?: Array<EmployeeWorkSchedule>;
  id: string;
  images: string;
  img: string | null;
  latLng: JsonValue;
  location: JsonValue;
  logo: string | null;
  name: string;
  open: boolean | null;
  openTime: Date | null;
  orders?: Array<Order>;
  phone: string;
  queues?: Array<Queue>;
  salonAccounts?: Array<SalonAccount>;
  salonRatingLikes?: Array<SalonRatingLike>;
  salonRatings?: Array<SalonRating>;
  salonServices?: Array<SalonService>;
  timeSlots?: Array<TimeSlot>;
  timezone: string;
  updatedAt: Date | null;
  userAccounts?: Array<UserAccount>;
  userFavoriteSalons?: Array<UserFavoriteSalon>;
  userProfilesSalonsSalonAdminIdTouserProfiles?: UserProfile | null;
  userProfilesUserProfilesSalonIdTosalons?: Array<UserProfile>;
  website: string | null;
};
