/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsEnum,
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumMfaFactorFactorType } from "./EnumMfaFactorFactorType";
import { MfaChallengeCreateNestedManyWithoutMfaFactorsInput } from "./MfaChallengeCreateNestedManyWithoutMfaFactorsInput";
import { EnumMfaFactorStatus } from "./EnumMfaFactorStatus";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class MfaFactorCreateInput {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    enum: EnumMfaFactorFactorType,
  })
  @IsEnum(EnumMfaFactorFactorType)
  @Field(() => EnumMfaFactorFactorType)
  factor_type!: "totp" | "webauthn" | "phone";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  friendlyName?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  lastChallengedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => MfaChallengeCreateNestedManyWithoutMfaFactorsInput,
  })
  @ValidateNested()
  @Type(() => MfaChallengeCreateNestedManyWithoutMfaFactorsInput)
  @IsOptional()
  @Field(() => MfaChallengeCreateNestedManyWithoutMfaFactorsInput, {
    nullable: true,
  })
  mfaChallenges?: MfaChallengeCreateNestedManyWithoutMfaFactorsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  secret?: string | null;

  @ApiProperty({
    required: true,
    enum: EnumMfaFactorStatus,
  })
  @IsEnum(EnumMfaFactorStatus)
  @Field(() => EnumMfaFactorStatus)
  status!: "unverified" | "verified";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  users!: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  webAuthnAaguid?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  webAuthnCredential?: InputJsonValue;
}

export { MfaFactorCreateInput as MfaFactorCreateInput };
