import { Decimal } from "decimal.js";
import { SalonWhereUniqueInput } from "../salon/SalonWhereUniqueInput";
import { UserProfileWhereUniqueInput } from "../userProfile/UserProfileWhereUniqueInput";

export type EmployeeStatUpdateInput = {
  averageOrderAmount?: Decimal | null;
  averageOrderDuration?: number | null;
  averageRating?: Decimal | null;
  averageServiceTime?: number | null;
  canceledOrdersCount?: Decimal | null;
  cardPaymentsAmount?: Decimal | null;
  cashPaymentsAmount?: Decimal | null;
  consistencyScore?: Decimal | null;
  conversionRate?: Decimal | null;
  currentMonthOrders?: number | null;
  currentMonthRevenue?: Decimal | null;
  efficiencyChangePercent?: Decimal | null;
  efficiencyRate?: Decimal | null;
  efficiencyScore?: Decimal | null;
  efficiencyTrend?: string | null;
  executionRate?: Decimal | null;
  fillRate?: Decimal | null;
  lastOrderAt?: Date | null;
  negativeReviews?: number | null;
  ordersChangePercent?: Decimal | null;
  ordersGrowthRate?: Decimal | null;
  ordersPerDay?: Decimal | null;
  ordersTrend?: string | null;
  overtimeCount?: number | null;
  peakHoursOrders?: number | null;
  peakPerformanceRate?: Decimal | null;
  performanceChangePercent?: Decimal | null;
  performanceScore?: Decimal | null;
  performanceTrend?: string | null;
  positiveReviews?: number | null;
  prevMonthEfficiencyRate?: Decimal | null;
  prevMonthPerformanceScore?: Decimal | null;
  prevMonthTotalOrders?: number | null;
  prevMonthTotalRevenue?: Decimal | null;
  previousMonthOrders?: number | null;
  previousMonthRevenue?: Decimal | null;
  qualityScore?: Decimal | null;
  rating?: Decimal | null;
  ratingChangePercent?: Decimal | null;
  ratingTrend?: string | null;
  revenueChangePercent?: Decimal | null;
  revenueGrowthRate?: Decimal | null;
  revenuePerHour?: Decimal | null;
  revenueTrend?: string | null;
  salons?: SalonWhereUniqueInput;
  servicesChangePercent?: Decimal | null;
  servicesGrowthRate?: Decimal | null;
  servicesPerHour?: Decimal | null;
  servicesTrend?: string | null;
  totalDowntimeHours?: Decimal | null;
  totalExecutionTime?: Decimal | null;
  totalIdleTime?: Decimal | null;
  totalOrders?: number | null;
  totalRatings?: number | null;
  totalRevenue?: Decimal | null;
  totalServices?: number | null;
  totalWorkTime?: number | null;
  totalWorkedHours?: Decimal | null;
  userProfiles?: UserProfileWhereUniqueInput;
  utilizationRate?: Decimal | null;
  workloadPercentage?: Decimal | null;
  yearToDateOrders?: number | null;
  yearToDateRevenue?: Decimal | null;
  yearToDateServices?: number | null;
};
