import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { SalonWhereUniqueInput } from "../salon/SalonWhereUniqueInput";
import { UserProfileWhereUniqueInput } from "../userProfile/UserProfileWhereUniqueInput";

export type EmployeeStatWhereInput = {
  averageOrderAmount?: DecimalNullableFilter;
  averageOrderDuration?: IntNullableFilter;
  averageRating?: DecimalNullableFilter;
  averageServiceTime?: IntNullableFilter;
  canceledOrdersCount?: DecimalNullableFilter;
  cardPaymentsAmount?: DecimalNullableFilter;
  cashPaymentsAmount?: DecimalNullableFilter;
  consistencyScore?: DecimalNullableFilter;
  conversionRate?: DecimalNullableFilter;
  createdAt?: DateTimeNullableFilter;
  currentMonthOrders?: IntNullableFilter;
  currentMonthRevenue?: DecimalNullableFilter;
  efficiencyChangePercent?: DecimalNullableFilter;
  efficiencyRate?: DecimalNullableFilter;
  efficiencyScore?: DecimalNullableFilter;
  efficiencyTrend?: StringNullableFilter;
  executionRate?: DecimalNullableFilter;
  fillRate?: DecimalNullableFilter;
  id?: StringFilter;
  lastOrderAt?: DateTimeNullableFilter;
  negativeReviews?: IntNullableFilter;
  ordersChangePercent?: DecimalNullableFilter;
  ordersGrowthRate?: DecimalNullableFilter;
  ordersPerDay?: DecimalNullableFilter;
  ordersTrend?: StringNullableFilter;
  overtimeCount?: IntNullableFilter;
  peakHoursOrders?: IntNullableFilter;
  peakPerformanceRate?: DecimalNullableFilter;
  performanceChangePercent?: DecimalNullableFilter;
  performanceScore?: DecimalNullableFilter;
  performanceTrend?: StringNullableFilter;
  positiveReviews?: IntNullableFilter;
  prevMonthEfficiencyRate?: DecimalNullableFilter;
  prevMonthPerformanceScore?: DecimalNullableFilter;
  prevMonthTotalOrders?: IntNullableFilter;
  prevMonthTotalRevenue?: DecimalNullableFilter;
  previousMonthOrders?: IntNullableFilter;
  previousMonthRevenue?: DecimalNullableFilter;
  qualityScore?: DecimalNullableFilter;
  rating?: DecimalNullableFilter;
  ratingChangePercent?: DecimalNullableFilter;
  ratingTrend?: StringNullableFilter;
  revenueChangePercent?: DecimalNullableFilter;
  revenueGrowthRate?: DecimalNullableFilter;
  revenuePerHour?: DecimalNullableFilter;
  revenueTrend?: StringNullableFilter;
  salons?: SalonWhereUniqueInput;
  servicesChangePercent?: DecimalNullableFilter;
  servicesGrowthRate?: DecimalNullableFilter;
  servicesPerHour?: DecimalNullableFilter;
  servicesTrend?: StringNullableFilter;
  totalDowntimeHours?: DecimalNullableFilter;
  totalExecutionTime?: DecimalNullableFilter;
  totalIdleTime?: DecimalNullableFilter;
  totalOrders?: IntNullableFilter;
  totalRatings?: IntNullableFilter;
  totalRevenue?: DecimalNullableFilter;
  totalServices?: IntNullableFilter;
  totalWorkTime?: IntNullableFilter;
  totalWorkedHours?: DecimalNullableFilter;
  updatedAt?: DateTimeNullableFilter;
  userProfiles?: UserProfileWhereUniqueInput;
  utilizationRate?: DecimalNullableFilter;
  workloadPercentage?: DecimalNullableFilter;
  yearToDateOrders?: IntNullableFilter;
  yearToDateRevenue?: DecimalNullableFilter;
  yearToDateServices?: IntNullableFilter;
};
