/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { MobilePaymentProviderService } from "../mobilePaymentProvider.service";
import { MobilePaymentProviderCreateInput } from "./MobilePaymentProviderCreateInput";
import { MobilePaymentProviderWhereInput } from "./MobilePaymentProviderWhereInput";
import { MobilePaymentProviderWhereUniqueInput } from "./MobilePaymentProviderWhereUniqueInput";
import { MobilePaymentProviderFindManyArgs } from "./MobilePaymentProviderFindManyArgs";
import { MobilePaymentProviderUpdateInput } from "./MobilePaymentProviderUpdateInput";
import { MobilePaymentProvider } from "./MobilePaymentProvider";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";

export class MobilePaymentProviderGrpcControllerBase {
  constructor(protected readonly service: MobilePaymentProviderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MobilePaymentProvider })
  @GrpcMethod("MobilePaymentProviderService", "createMobilePaymentProvider")
  async createMobilePaymentProvider(
    @common.Body() data: MobilePaymentProviderCreateInput
  ): Promise<MobilePaymentProvider> {
    return await this.service.createMobilePaymentProvider({
      data: data,
      select: {
        apiKey: true,
        apiSecret: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [MobilePaymentProvider] })
  @ApiNestedQuery(MobilePaymentProviderFindManyArgs)
  @GrpcMethod("MobilePaymentProviderService", "mobilePaymentProviders")
  async mobilePaymentProviders(
    @common.Req() request: Request
  ): Promise<MobilePaymentProvider[]> {
    const args = plainToClass(MobilePaymentProviderFindManyArgs, request.query);
    return this.service.mobilePaymentProviders({
      ...args,
      select: {
        apiKey: true,
        apiSecret: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MobilePaymentProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("MobilePaymentProviderService", "mobilePaymentProvider")
  async mobilePaymentProvider(
    @common.Param() params: MobilePaymentProviderWhereUniqueInput
  ): Promise<MobilePaymentProvider | null> {
    const result = await this.service.mobilePaymentProvider({
      where: params,
      select: {
        apiKey: true,
        apiSecret: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MobilePaymentProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("MobilePaymentProviderService", "updateMobilePaymentProvider")
  async updateMobilePaymentProvider(
    @common.Param() params: MobilePaymentProviderWhereUniqueInput,
    @common.Body() data: MobilePaymentProviderUpdateInput
  ): Promise<MobilePaymentProvider | null> {
    try {
      return await this.service.updateMobilePaymentProvider({
        where: params,
        data: data,
        select: {
          apiKey: true,
          apiSecret: true,
          createdAt: true,
          id: true,
          isActive: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MobilePaymentProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("MobilePaymentProviderService", "deleteMobilePaymentProvider")
  async deleteMobilePaymentProvider(
    @common.Param() params: MobilePaymentProviderWhereUniqueInput
  ): Promise<MobilePaymentProvider | null> {
    try {
      return await this.service.deleteMobilePaymentProvider({
        where: params,
        select: {
          apiKey: true,
          apiSecret: true,
          createdAt: true,
          id: true,
          isActive: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/payments")
  @ApiNestedQuery(PaymentFindManyArgs)
  @GrpcMethod("MobilePaymentProviderService", "findManyPayments")
  async findManyPayments(
    @common.Req() request: Request,
    @common.Param() params: MobilePaymentProviderWhereUniqueInput
  ): Promise<Payment[]> {
    const query = plainToClass(PaymentFindManyArgs, request.query);
    const results = await this.service.findPayments(params.id, {
      ...query,
      select: {
        amount: true,
        amountByCard: true,
        amountByCash: true,
        completed: true,
        completedAt: true,
        createdAt: true,
        discountAmount: true,
        id: true,
        isPartial: true,

        mobilePaymentProviders: {
          select: {
            id: true,
          },
        },

        name: true,
        orderId: true,
        payment_method: true,
        status: true,
        tax: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payments")
  @GrpcMethod("MobilePaymentProviderService", "connectPayments")
  async connectPayments(
    @common.Param() params: MobilePaymentProviderWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        connect: body,
      },
    };
    await this.service.updateMobilePaymentProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payments")
  @GrpcMethod("MobilePaymentProviderService", "updatePayments")
  async updatePayments(
    @common.Param() params: MobilePaymentProviderWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        set: body,
      },
    };
    await this.service.updateMobilePaymentProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payments")
  @GrpcMethod("MobilePaymentProviderService", "disconnectPayments")
  async disconnectPayments(
    @common.Param() params: MobilePaymentProviderWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        disconnect: body,
      },
    };
    await this.service.updateMobilePaymentProvider({
      where: params,
      data,
      select: { id: true },
    });
  }
}
