/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { MobilePaymentProvider } from "./MobilePaymentProvider";
import { MobilePaymentProviderCountArgs } from "./MobilePaymentProviderCountArgs";
import { MobilePaymentProviderFindManyArgs } from "./MobilePaymentProviderFindManyArgs";
import { MobilePaymentProviderFindUniqueArgs } from "./MobilePaymentProviderFindUniqueArgs";
import { CreateMobilePaymentProviderArgs } from "./CreateMobilePaymentProviderArgs";
import { UpdateMobilePaymentProviderArgs } from "./UpdateMobilePaymentProviderArgs";
import { DeleteMobilePaymentProviderArgs } from "./DeleteMobilePaymentProviderArgs";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { MobilePaymentProviderService } from "../mobilePaymentProvider.service";
@graphql.Resolver(() => MobilePaymentProvider)
export class MobilePaymentProviderResolverBase {
  constructor(protected readonly service: MobilePaymentProviderService) {}

  async _mobilePaymentProvidersMeta(
    @graphql.Args() args: MobilePaymentProviderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [MobilePaymentProvider])
  async mobilePaymentProviders(
    @graphql.Args() args: MobilePaymentProviderFindManyArgs
  ): Promise<MobilePaymentProvider[]> {
    return this.service.mobilePaymentProviders(args);
  }

  @graphql.Query(() => MobilePaymentProvider, { nullable: true })
  async mobilePaymentProvider(
    @graphql.Args() args: MobilePaymentProviderFindUniqueArgs
  ): Promise<MobilePaymentProvider | null> {
    const result = await this.service.mobilePaymentProvider(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MobilePaymentProvider)
  async createMobilePaymentProvider(
    @graphql.Args() args: CreateMobilePaymentProviderArgs
  ): Promise<MobilePaymentProvider> {
    return await this.service.createMobilePaymentProvider({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => MobilePaymentProvider)
  async updateMobilePaymentProvider(
    @graphql.Args() args: UpdateMobilePaymentProviderArgs
  ): Promise<MobilePaymentProvider | null> {
    try {
      return await this.service.updateMobilePaymentProvider({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MobilePaymentProvider)
  async deleteMobilePaymentProvider(
    @graphql.Args() args: DeleteMobilePaymentProviderArgs
  ): Promise<MobilePaymentProvider | null> {
    try {
      return await this.service.deleteMobilePaymentProvider(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Payment], { name: "payments" })
  async findPayments(
    @graphql.Parent() parent: MobilePaymentProvider,
    @graphql.Args() args: PaymentFindManyArgs
  ): Promise<Payment[]> {
    const results = await this.service.findPayments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
