import { Decimal } from "decimal.js";
import { SalonWhereUniqueInput } from "../salon/SalonWhereUniqueInput";
import { UserProfileWhereUniqueInput } from "../userProfile/UserProfileWhereUniqueInput";

export type EmployeeDailyStatCreateInput = {
  averageOrderAmount?: Decimal | null;
  averageServiceTime?: number | null;
  avgServiceTimeChangePercent?: Decimal | null;
  avgServiceTimeTrend?: string | null;
  bestServiceTime?: Date | null;
  canceledOrders?: number | null;
  cardRevenue?: Decimal | null;
  cashRevenue?: Decimal | null;
  clientsChangePercent?: Decimal | null;
  clientsTrend?: string | null;
  completedOrders?: number | null;
  dailyRating?: Decimal | null;
  date: Date;
  efficiencyChangePercent?: Decimal | null;
  efficiencyRate?: Decimal | null;
  efficiencyTrend?: string | null;
  firstOrderTime?: Date | null;
  lastOrderTime?: Date | null;
  monthToDateOrders?: number | null;
  monthToDateRevenue?: Decimal | null;
  newClients?: number | null;
  offPeakOrders?: number | null;
  ordersChangePercent?: Decimal | null;
  ordersCount?: number | null;
  ordersTrend?: string | null;
  overtimeHours?: Decimal | null;
  peakHoursOrders?: number | null;
  performanceScore?: Decimal | null;
  prevMonthOrders?: number | null;
  prevMonthRevenue?: Decimal | null;
  ratingChangePercent?: Decimal | null;
  ratingTrend?: string | null;
  ratingsCount?: number | null;
  repeatClients?: number | null;
  revenue?: Decimal | null;
  revenueChangePercent?: Decimal | null;
  revenueTrend?: string | null;
  salons: SalonWhereUniqueInput;
  scheduledHours?: Decimal | null;
  servicesCount?: number | null;
  totalBreaksTime?: number | null;
  totalClients?: number | null;
  totalIdleTime?: number | null;
  totalWorkedHours?: Decimal | null;
  userProfiles: UserProfileWhereUniqueInput;
  workTime?: number | null;
  worstServiceTime?: Date | null;
};
