import { Identity } from "../identity/Identity";
import { MfaFactor } from "../mfaFactor/MfaFactor";
import { OneTimeToken } from "../oneTimeToken/OneTimeToken";
import { JsonValue } from "type-fest";
import { Session } from "../session/Session";

export type User = {
  aud: string | null;
  bannedUntil: Date | null;
  confirmationSentAt: Date | null;
  confirmationToken: string | null;
  confirmedAt: Date | null;
  createdAt: Date | null;
  deletedAt: Date | null;
  email: string | null;
  emailChange: string | null;
  emailChangeConfirmStatus: number | null;
  emailChangeSentAt: Date | null;
  emailChangeTokenCurrent: string | null;
  emailChangeTokenNew: string | null;
  emailConfirmedAt: Date | null;
  id: string;
  identities?: Array<Identity>;
  instanceId: string | null;
  invitedAt: Date | null;
  isAnonymous: boolean;
  isSsoUser: boolean;
  isSuperAdmin: boolean | null;
  lastSignInAt: Date | null;
  mfaFactors?: Array<MfaFactor>;
  oneTimeTokens?: Array<OneTimeToken>;
  phone: string | null;
  phoneChange: string | null;
  phoneChangeSentAt: Date | null;
  phoneChangeToken: string | null;
  phoneConfirmedAt: Date | null;
  rawAppMetaData: JsonValue;
  rawUserMetaData: JsonValue;
  reauthenticationSentAt: Date | null;
  reauthenticationToken: string | null;
  recoverySentAt: Date | null;
  recoveryToken: string | null;
  roles: JsonValue;
  sessions?: Array<Session>;
  updatedAt: Date | null;
  username: string | null;
};
