import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IdentityListRelationFilter } from "../identity/IdentityListRelationFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { MfaFactorListRelationFilter } from "../mfaFactor/MfaFactorListRelationFilter";
import { OneTimeTokenListRelationFilter } from "../oneTimeToken/OneTimeTokenListRelationFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { SessionListRelationFilter } from "../session/SessionListRelationFilter";

export type UserWhereInput = {
  aud?: StringNullableFilter;
  bannedUntil?: DateTimeNullableFilter;
  confirmationSentAt?: DateTimeNullableFilter;
  confirmationToken?: StringNullableFilter;
  confirmedAt?: DateTimeNullableFilter;
  createdAt?: DateTimeNullableFilter;
  deletedAt?: DateTimeNullableFilter;
  email?: StringNullableFilter;
  emailChange?: StringNullableFilter;
  emailChangeConfirmStatus?: IntNullableFilter;
  emailChangeSentAt?: DateTimeNullableFilter;
  emailChangeTokenCurrent?: StringNullableFilter;
  emailChangeTokenNew?: StringNullableFilter;
  emailConfirmedAt?: DateTimeNullableFilter;
  id?: StringFilter;
  identities?: IdentityListRelationFilter;
  instanceId?: StringNullableFilter;
  invitedAt?: DateTimeNullableFilter;
  isAnonymous?: BooleanFilter;
  isSsoUser?: BooleanFilter;
  isSuperAdmin?: BooleanNullableFilter;
  lastSignInAt?: DateTimeNullableFilter;
  mfaFactors?: MfaFactorListRelationFilter;
  oneTimeTokens?: OneTimeTokenListRelationFilter;
  phone?: StringNullableFilter;
  phoneChange?: StringNullableFilter;
  phoneChangeSentAt?: DateTimeNullableFilter;
  phoneChangeToken?: StringNullableFilter;
  phoneConfirmedAt?: DateTimeNullableFilter;
  rawAppMetaData?: JsonFilter;
  rawUserMetaData?: JsonFilter;
  reauthenticationSentAt?: DateTimeNullableFilter;
  reauthenticationToken?: StringNullableFilter;
  recoverySentAt?: DateTimeNullableFilter;
  recoveryToken?: StringNullableFilter;
  sessions?: SessionListRelationFilter;
  updatedAt?: DateTimeNullableFilter;
};
