import { SortOrder } from "../../util/SortOrder";

export type UserOrderByInput = {
  aud?: SortOrder;
  bannedUntil?: SortOrder;
  confirmationSentAt?: SortOrder;
  confirmationToken?: SortOrder;
  confirmedAt?: SortOrder;
  createdAt?: SortOrder;
  deletedAt?: SortOrder;
  email?: SortOrder;
  emailChange?: SortOrder;
  emailChangeConfirmStatus?: SortOrder;
  emailChangeSentAt?: SortOrder;
  emailChangeTokenCurrent?: SortOrder;
  emailChangeTokenNew?: SortOrder;
  emailConfirmedAt?: SortOrder;
  id?: SortOrder;
  instanceId?: SortOrder;
  invitedAt?: SortOrder;
  isAnonymous?: SortOrder;
  isSsoUser?: SortOrder;
  isSuperAdmin?: SortOrder;
  lastSignInAt?: SortOrder;
  password?: SortOrder;
  phone?: SortOrder;
  phoneChange?: SortOrder;
  phoneChangeSentAt?: SortOrder;
  phoneChangeToken?: SortOrder;
  phoneConfirmedAt?: SortOrder;
  rawAppMetaData?: SortOrder;
  rawUserMetaData?: SortOrder;
  reauthenticationSentAt?: SortOrder;
  reauthenticationToken?: SortOrder;
  recoverySentAt?: SortOrder;
  recoveryToken?: SortOrder;
  roles?: SortOrder;
  updatedAt?: SortOrder;
  username?: SortOrder;
};
