import { IdentityCreateNestedManyWithoutUsersInput } from "./IdentityCreateNestedManyWithoutUsersInput";
import { MfaFactorCreateNestedManyWithoutUsersInput } from "./MfaFactorCreateNestedManyWithoutUsersInput";
import { OneTimeTokenCreateNestedManyWithoutUsersInput } from "./OneTimeTokenCreateNestedManyWithoutUsersInput";
import { InputJsonValue } from "../../types";
import { SessionCreateNestedManyWithoutUsersInput } from "./SessionCreateNestedManyWithoutUsersInput";

export type UserCreateInput = {
  aud?: string | null;
  bannedUntil?: Date | null;
  confirmationSentAt?: Date | null;
  confirmationToken?: string | null;
  confirmedAt?: Date | null;
  createdAt?: Date | null;
  deletedAt?: Date | null;
  email?: string | null;
  emailChange?: string | null;
  emailChangeConfirmStatus?: number | null;
  emailChangeSentAt?: Date | null;
  emailChangeTokenCurrent?: string | null;
  emailChangeTokenNew?: string | null;
  emailConfirmedAt?: Date | null;
  identities?: IdentityCreateNestedManyWithoutUsersInput;
  instanceId?: string | null;
  invitedAt?: Date | null;
  isAnonymous: boolean;
  isSsoUser: boolean;
  isSuperAdmin?: boolean | null;
  lastSignInAt?: Date | null;
  mfaFactors?: MfaFactorCreateNestedManyWithoutUsersInput;
  oneTimeTokens?: OneTimeTokenCreateNestedManyWithoutUsersInput;
  password?: string | null;
  phone?: string | null;
  phoneChange?: string | null;
  phoneChangeSentAt?: Date | null;
  phoneChangeToken?: string | null;
  phoneConfirmedAt?: Date | null;
  rawAppMetaData?: InputJsonValue;
  rawUserMetaData?: InputJsonValue;
  reauthenticationSentAt?: Date | null;
  reauthenticationToken?: string | null;
  recoverySentAt?: Date | null;
  recoveryToken?: string | null;
  roles: InputJsonValue;
  sessions?: SessionCreateNestedManyWithoutUsersInput;
  updatedAt?: Date | null;
  username?: string | null;
};
